#!/bin/bash

conda install -c conda-forge xeus-cling
jupyter lab workspaces import binder/workspace.json

cd ~/cgen
g++ skel.cpp -o skel
g++ cgen.cpp lexer.cpp parse.cpp -o cgen

mv skel ~/bin/skel
mv cgen ~/bin/cgen

chmod 755 ~/bin/skel
chmod 755 ~/bin/cgen
